version: '2'
services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./assets/nginx:/etc/nginx/conf.d:ro
      - ./static:/static:ro
      - ./data:/data:ro
    ports:
      - "127.0.0.1:8000:8000"
